<?php

declare(strict_types=1);

/*
 * This file is part of the UhifadhiLabs Roster Module.
 *
 * (c) Ezekiel Mjema <https://github.com/eemjema>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Uhifadhi\Roster\Migrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * WHAT THE CONFIGURE PAGE WRITES — the four columns this module owns on a
 * station, and the answers it cannot guess about an organization.
 *
 * TWO NEW TABLES AND NOTHING TOUCHED. No column is added to a table that
 * already has rows, so there is nothing to expand, backfill or contract; the
 * discipline applies from the first migration that changes something that
 * already exists.
 *
 * NEITHER ROW IS CREATED HERE. A settings row is written the first time an
 * area is asked what it runs on, and a watch is written when somebody puts a
 * post on the roster's books — deliberately, because a watch seeded for every
 * station would put twelve posts on the books that nobody meant to be
 * watching.
 */
final class Version20260920000100 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'The watch a station expects, and an area\'s roster settings';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE roster_station_watch (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, expects JSON NOT NULL, silence_window_minutes INT NOT NULL, offline_after_minutes INT NOT NULL, catchment_metres INT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, station_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_roster_watch_station ON roster_station_watch (station_id)');
        $this->addSql('CREATE TABLE roster_area_settings (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, ping_interval_minutes INT NOT NULL, off_day_has_no_state BOOLEAN NOT NULL, leave_approval_shown BOOLEAN NOT NULL, default_catchment_metres INT NOT NULL, late_threshold VARCHAR(32) NOT NULL, vacancy_announce VARCHAR(32) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, area_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_roster_settings_area ON roster_area_settings (area_id)');
        $this->addSql('ALTER TABLE roster_station_watch ADD CONSTRAINT FK_8D3C2D0821BDB235 FOREIGN KEY (station_id) REFERENCES station (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE roster_area_settings ADD CONSTRAINT FK_A3FBE615BD0F409C FOREIGN KEY (area_id) REFERENCES area_of_interest (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE IF EXISTS roster_station_watch CASCADE');
        $this->addSql('DROP TABLE IF EXISTS roster_area_settings CASCADE');
    }
}
