<?php

declare(strict_types=1);

/*
 * This file is part of the UhifadhiLabs Roster Module.
 *
 * (c) Ezekiel Mjema <https://github.com/eemjema>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Uhifadhi\Roster\Migrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * THE CONFIGURE REDESIGN'S SCHEMA — a shift's colour, the five rules and
 * their per-station exceptions, and the pattern.
 *
 * EXPAND AND BACKFILL, AND NOTHING DROPPED. Every existing surface — the
 * rota, the day board, the plan sheet, the generator, the organization
 * dashboard — still reads `roster_rotation` and it is left exactly as it
 * is. What this migration does is give the new model the same facts, so
 * the two agree from the moment it runs; the DESTRUCTIVE half, dropping
 * the ring's own columns once nothing reads them, rides a later release
 * as the module's own rule requires.
 *
 * WHAT IS CARRIED FORWARD, and from where:
 *
 *   a shift's colour   → the slot it gets is its POSITION in the area's
 *                        list, wrapped into the palette's eighteen. It is
 *                        the only stable thing about an existing shift
 *                        that differs between shifts, and after this the
 *                        stored value is what every surface reads, so
 *                        reordering the list never recolours anything
 *                        again.
 *   the five rules     → from `roster_area_settings`, which is where three
 *                        of them already lived: the ping interval and the
 *                        default catchment verbatim, and late-after from
 *                        the area's own threshold where it named a fixed
 *                        one. The two nobody had a column for start at the
 *                        product's standard.
 *   an exception       → from `roster_station_watch`, whose silence and
 *                        offline windows were already per station. A
 *                        station whose window MATCHES the area's default
 *                        gets no row: following the area is said by the
 *                        absence of an exception, so backfilling one for
 *                        every station would turn twelve defaults into
 *                        twelve exceptions and the card would read as if
 *                        nothing agreed with anything.
 *   a pattern          → one per DISTINCT cycle in the area, and each
 *                        station's watch is pointed at the pattern its own
 *                        ring made. Two stations running the same cycle
 *                        become two stations running one pattern, which is
 *                        the ruling ("one object at area level") applied
 *                        to the data that already existed.
 *   what a station needs → from that station's ring, `slots_per_shift`,
 *                        which is where it lived when a ring was per
 *                        station. It belongs to the station now, because a
 *                        pattern is shared and how many people a place
 *                        needs is not a fact about a cycle.
 */
final class Version20260921000000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'A shift keeps a colour; the five rules, their station exceptions, and the pattern';
    }

    public function up(Schema $schema): void
    {
        // ── the shift's stored colour ────────────────────────────────────
        // Added with the palette's first slot so the column can be NOT NULL
        // on a populated table in one statement, then given each shift its
        // own slot from its position in its area's list, and tightened.
        // Expand, backfill, contract — in this one migration, so a failure
        // leaves the table as it was and nobody edits a vendor file.
        $this->addSql('ALTER TABLE roster_shift ADD colour INT DEFAULT NULL');
        $this->addSql(<<<'SQL'
            UPDATE roster_shift s SET colour = n.slot
            FROM (
                SELECT id, 1 + ((ROW_NUMBER() OVER (PARTITION BY area_id ORDER BY position, id) - 1) % 18) AS slot
                FROM roster_shift
            ) n
            WHERE n.id = s.id
            SQL);

        // ── the five rules, per area ─────────────────────────────────────
        $this->addSql(<<<'SQL'
            CREATE TABLE roster_shift_rule (
                id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                uuid UUID NOT NULL,
                area_id INT NOT NULL,
                kind VARCHAR(32) NOT NULL,
                value DOUBLE PRECISION NOT NULL,
                unit VARCHAR(16) NOT NULL,
                created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
                updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
                PRIMARY KEY (id)
            )
            SQL);
        $this->addSql('CREATE UNIQUE INDEX uniq_roster_shift_rule_uuid ON roster_shift_rule (uuid)');
        $this->addSql('CREATE UNIQUE INDEX uniq_roster_rule_area_kind ON roster_shift_rule (area_id, kind)');
        $this->addSql('CREATE INDEX idx_roster_shift_rule_area ON roster_shift_rule (area_id)');
        $this->addSql('ALTER TABLE roster_shift_rule ADD CONSTRAINT fk_roster_shift_rule_area FOREIGN KEY (area_id) REFERENCES area_of_interest (id) ON DELETE CASCADE');

        // ── what one station does differently ────────────────────────────
        $this->addSql(<<<'SQL'
            CREATE TABLE roster_station_rule_exception (
                id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                uuid UUID NOT NULL,
                station_id INT NOT NULL,
                kind VARCHAR(32) NOT NULL,
                value DOUBLE PRECISION NOT NULL,
                unit VARCHAR(16) NOT NULL,
                created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
                updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
                PRIMARY KEY (id)
            )
            SQL);
        $this->addSql('CREATE UNIQUE INDEX uniq_roster_station_rule_exception_uuid ON roster_station_rule_exception (uuid)');
        $this->addSql('CREATE UNIQUE INDEX uniq_roster_exception_station_kind ON roster_station_rule_exception (station_id, kind)');
        $this->addSql('CREATE INDEX idx_roster_station_rule_exception_station ON roster_station_rule_exception (station_id)');
        $this->addSql('ALTER TABLE roster_station_rule_exception ADD CONSTRAINT fk_roster_station_rule_exception_station FOREIGN KEY (station_id) REFERENCES station (id) ON DELETE CASCADE');

        // ── the pattern ──────────────────────────────────────────────────
        $this->addSql(<<<'SQL'
            CREATE TABLE roster_pattern (
                id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                uuid UUID NOT NULL,
                area_id INT NOT NULL,
                cycle JSON NOT NULL,
                created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
                updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
                PRIMARY KEY (id)
            )
            SQL);
        $this->addSql('CREATE UNIQUE INDEX uniq_roster_pattern_uuid ON roster_pattern (uuid)');
        $this->addSql('CREATE INDEX idx_roster_pattern_area ON roster_pattern (area_id)');
        $this->addSql('ALTER TABLE roster_pattern ADD CONSTRAINT fk_roster_pattern_area FOREIGN KEY (area_id) REFERENCES area_of_interest (id) ON DELETE CASCADE');

        // ── what the station keeps of its own ────────────────────────────
        $this->addSql('ALTER TABLE roster_station_watch ADD needs_per_shift JSON DEFAULT NULL');
        $this->addSql('ALTER TABLE roster_station_watch ADD pattern_id INT DEFAULT NULL');
        $this->addSql('CREATE INDEX idx_roster_station_watch_pattern ON roster_station_watch (pattern_id)');
        $this->addSql('ALTER TABLE roster_station_watch ADD CONSTRAINT fk_roster_station_watch_pattern FOREIGN KEY (pattern_id) REFERENCES roster_pattern (id) ON DELETE SET NULL');

        $this->backfillTheRules();
        $this->backfillTheExceptions();
        $this->backfillThePatterns();

        // ── and the two new columns are required, now they are filled ────
        $this->addSql('UPDATE roster_shift SET colour = 1 WHERE colour IS NULL');
        $this->addSql('ALTER TABLE roster_shift ALTER colour SET NOT NULL');
        $this->addSql("UPDATE roster_station_watch SET needs_per_shift = '{}' WHERE needs_per_shift IS NULL");
        $this->addSql('ALTER TABLE roster_station_watch ALTER needs_per_shift SET NOT NULL');
    }

    /**
     * THE AREA'S FIVE, from where three of them already lived.
     *
     * `late_threshold` is an enum of three answers and only two of them
     * name a number; `2x` means twice the ping interval, which is not a
     * fixed threshold at all, so an area on it starts at the product's
     * standard rather than at a number this migration invented.
     */
    private function backfillTheRules(): void
    {
        $this->addSql(<<<'SQL'
            INSERT INTO roster_shift_rule (uuid, area_id, kind, value, unit, created_at, updated_at)
            SELECT gen_random_uuid(), s.area_id, v.kind, v.value, v.unit, NOW(), NOW()
            FROM roster_area_settings s
            CROSS JOIN LATERAL (VALUES
                ('ping_every',      s.ping_interval_minutes::double precision, 'minutes'),
                ('check_in_within', s.default_catchment_metres::double precision, 'm'),
                ('late_after',      CASE s.late_threshold WHEN '1h' THEN 1 WHEN '4h' THEN 4 ELSE 2 END::double precision, 'hours'),
                ('offline_after',   1::double precision, 'days'),
                ('raise_unfilled',  4::double precision, 'hours')
            ) AS v(kind, value, unit)
            ON CONFLICT (area_id, kind) DO NOTHING
            SQL);
    }

    /**
     * A STATION THAT ALREADY DIFFERED KEEPS DIFFERING, and one that agreed
     * with its area says nothing.
     *
     * The comparison is in MINUTES on both sides, because the area's value
     * is stored in minutes and the station's window is too — so "2 hours"
     * and "120 minutes" compare equal and do not become an exception that
     * changes nothing.
     */
    private function backfillTheExceptions(): void
    {
        $this->addSql(<<<'SQL'
            INSERT INTO roster_station_rule_exception (uuid, station_id, kind, value, unit, created_at, updated_at)
            SELECT gen_random_uuid(), w.station_id, 'late_after', w.silence_window_minutes::double precision, 'minutes', NOW(), NOW()
            FROM roster_station_watch w
            JOIN station st ON st.id = w.station_id
            JOIN roster_shift_rule r ON r.area_id = st.area_id AND r.kind = 'late_after'
            WHERE w.silence_window_minutes <> (r.value * CASE r.unit WHEN 'hours' THEN 60 WHEN 'days' THEN 1440 ELSE 1 END)
            ON CONFLICT (station_id, kind) DO NOTHING
            SQL);

        $this->addSql(<<<'SQL'
            INSERT INTO roster_station_rule_exception (uuid, station_id, kind, value, unit, created_at, updated_at)
            SELECT gen_random_uuid(), w.station_id, 'offline_after', w.offline_after_minutes::double precision, 'minutes', NOW(), NOW()
            FROM roster_station_watch w
            JOIN station st ON st.id = w.station_id
            JOIN roster_shift_rule r ON r.area_id = st.area_id AND r.kind = 'offline_after'
            WHERE w.offline_after_minutes <> (r.value * CASE r.unit WHEN 'hours' THEN 60 WHEN 'days' THEN 1440 ELSE 1 END)
            ON CONFLICT (station_id, kind) DO NOTHING
            SQL);

        // AND THE STATION'S OWN CATCHMENT, which the area module keeps on
        // the station itself. A station carrying none follows the area,
        // and says so by having no row here either.
        $this->addSql(<<<'SQL'
            INSERT INTO roster_station_rule_exception (uuid, station_id, kind, value, unit, created_at, updated_at)
            SELECT gen_random_uuid(), st.id, 'check_in_within', st.catchment_m::double precision, 'm', NOW(), NOW()
            FROM station st
            JOIN roster_station_watch w ON w.station_id = st.id
            JOIN roster_shift_rule r ON r.area_id = st.area_id AND r.kind = 'check_in_within'
            WHERE st.catchment_m IS NOT NULL
              AND st.catchment_m <> (r.value * CASE r.unit WHEN 'km' THEN 1000 ELSE 1 END)
            ON CONFLICT (station_id, kind) DO NOTHING
            SQL);
    }

    /**
     * ONE PATTERN PER DISTINCT CYCLE IN AN AREA, and every station's watch
     * pointed at the one its own ring made.
     *
     * A PER-TEAM ROTATION CONTRIBUTES ITS CYCLE AND NO LINK: it is filed
     * at a base station rather than run by one, and pointing that
     * station's watch at the squad's cycle would say the station is filled
     * from it, which it is not.
     *
     * GROUPED BY THE CYCLE AS TEXT, because Postgres gives `json` no
     * equality operator at all — two identical rings are not comparable as
     * json, and `DISTINCT` on the column fails outright rather than
     * quietly doing the wrong thing.
     */
    private function backfillThePatterns(): void
    {
        $this->addSql(<<<'SQL'
            INSERT INTO roster_pattern (uuid, area_id, cycle, created_at, updated_at)
            SELECT gen_random_uuid(), d.area_id, d.c::json, NOW(), NOW()
            FROM (SELECT area_id, cycle::text AS c FROM roster_rotation GROUP BY area_id, cycle::text) d
            SQL);

        $this->addSql(<<<'SQL'
            UPDATE roster_station_watch w
            SET pattern_id = p.id
            FROM roster_rotation ro
            JOIN station st ON st.id = ro.station_id
            JOIN roster_pattern p ON p.area_id = ro.area_id AND p.cycle::text = ro.cycle::text
            WHERE ro.station_id = w.station_id AND ro.active = TRUE
            SQL);

        // AND WHAT THE STATION NEEDS, off the ring that used to hold it.
        $this->addSql(<<<'SQL'
            UPDATE roster_station_watch w
            SET needs_per_shift = ro.slots_per_shift
            FROM roster_rotation ro
            WHERE ro.station_id = w.station_id
            SQL);
    }

    /**
     * NOTHING IN `up()` IS DESTRUCTIVE, which is why there is no
     * `@destructive` marker: the ring keeps every column it had, and the
     * release that stops reading them is the one that drops them.
     */
    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE roster_station_watch DROP CONSTRAINT IF EXISTS fk_roster_station_watch_pattern');
        $this->addSql('DROP INDEX IF EXISTS idx_roster_station_watch_pattern');
        $this->addSql('ALTER TABLE roster_station_watch DROP COLUMN IF EXISTS pattern_id');
        $this->addSql('ALTER TABLE roster_station_watch DROP COLUMN IF EXISTS needs_per_shift');
        $this->addSql('DROP TABLE IF EXISTS roster_pattern');
        $this->addSql('DROP TABLE IF EXISTS roster_station_rule_exception');
        $this->addSql('DROP TABLE IF EXISTS roster_shift_rule');
        $this->addSql('ALTER TABLE roster_shift DROP COLUMN IF EXISTS colour');
    }
}
