<?php

declare(strict_types=1);

/*
 * This file is part of the UhifadhiLabs Roster Module.
 *
 * (c) Ezekiel Mjema <https://github.com/eemjema>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Uhifadhi\Roster\Migrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * THE ROSTER'S SETTINGS TABLE GOES. Its ping interval was Settings › Core's
 * already; its four stored answers — off days on a tour, leave approval,
 * announcing vacancies, the late threshold — were read by nothing (ruled
 * 2 Oct 2026: they return with the feature that reads them); and a new post's
 * ring is the area's Check-in within rule. A clean start: nothing is copied.
 *
 * @destructive roster 0.2.0 — drops every area's roster settings row; the code
 *              that read them goes in the same release (a clean start, ruled
 *              1–2 Oct 2026).
 */
final class Version20261002000100 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'roster_area_settings goes: the roster keeps no settings of its own';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('DROP TABLE roster_area_settings');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('CREATE TABLE roster_area_settings (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, ping_interval_minutes INT NOT NULL, off_day_has_no_state BOOLEAN NOT NULL, leave_approval_shown BOOLEAN NOT NULL, default_catchment_metres INT NOT NULL, late_threshold VARCHAR(32) NOT NULL, vacancy_announce VARCHAR(32) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, area_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_roster_settings_area ON roster_area_settings (area_id)');
        $this->addSql('ALTER TABLE roster_area_settings ADD CONSTRAINT FK_A3FBE615BD0F409C FOREIGN KEY (area_id) REFERENCES area_of_interest (id) ON DELETE CASCADE NOT DEFERRABLE');
    }
}
